// Code generated by go-swagger; DO NOT EDIT.

package current_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCurrentUserParams creates a new DeleteCurrentUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCurrentUserParams() *DeleteCurrentUserParams {
	return &DeleteCurrentUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCurrentUserParamsWithTimeout creates a new DeleteCurrentUserParams object
// with the ability to set a timeout on a request.
func NewDeleteCurrentUserParamsWithTimeout(timeout time.Duration) *DeleteCurrentUserParams {
	return &DeleteCurrentUserParams{
		timeout: timeout,
	}
}

// NewDeleteCurrentUserParamsWithContext creates a new DeleteCurrentUserParams object
// with the ability to set a context for a request.
func NewDeleteCurrentUserParamsWithContext(ctx context.Context) *DeleteCurrentUserParams {
	return &DeleteCurrentUserParams{
		Context: ctx,
	}
}

// NewDeleteCurrentUserParamsWithHTTPClient creates a new DeleteCurrentUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCurrentUserParamsWithHTTPClient(client *http.Client) *DeleteCurrentUserParams {
	return &DeleteCurrentUserParams{
		HTTPClient: client,
	}
}

/* DeleteCurrentUserParams contains all the parameters to send to the API endpoint
   for the delete current user operation.

   Typically these are written to a http.Request.
*/
type DeleteCurrentUserParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete current user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCurrentUserParams) WithDefaults() *DeleteCurrentUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete current user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCurrentUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete current user params
func (o *DeleteCurrentUserParams) WithTimeout(timeout time.Duration) *DeleteCurrentUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete current user params
func (o *DeleteCurrentUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete current user params
func (o *DeleteCurrentUserParams) WithContext(ctx context.Context) *DeleteCurrentUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete current user params
func (o *DeleteCurrentUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete current user params
func (o *DeleteCurrentUserParams) WithHTTPClient(client *http.Client) *DeleteCurrentUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete current user params
func (o *DeleteCurrentUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCurrentUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
