// Code generated by go-swagger; DO NOT EDIT.

package current_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCurrentUserInvitesParams creates a new GetCurrentUserInvitesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCurrentUserInvitesParams() *GetCurrentUserInvitesParams {
	return &GetCurrentUserInvitesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserInvitesParamsWithTimeout creates a new GetCurrentUserInvitesParams object
// with the ability to set a timeout on a request.
func NewGetCurrentUserInvitesParamsWithTimeout(timeout time.Duration) *GetCurrentUserInvitesParams {
	return &GetCurrentUserInvitesParams{
		timeout: timeout,
	}
}

// NewGetCurrentUserInvitesParamsWithContext creates a new GetCurrentUserInvitesParams object
// with the ability to set a context for a request.
func NewGetCurrentUserInvitesParamsWithContext(ctx context.Context) *GetCurrentUserInvitesParams {
	return &GetCurrentUserInvitesParams{
		Context: ctx,
	}
}

// NewGetCurrentUserInvitesParamsWithHTTPClient creates a new GetCurrentUserInvitesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCurrentUserInvitesParamsWithHTTPClient(client *http.Client) *GetCurrentUserInvitesParams {
	return &GetCurrentUserInvitesParams{
		HTTPClient: client,
	}
}

/* GetCurrentUserInvitesParams contains all the parameters to send to the API endpoint
   for the get current user invites operation.

   Typically these are written to a http.Request.
*/
type GetCurrentUserInvitesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get current user invites params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserInvitesParams) WithDefaults() *GetCurrentUserInvitesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get current user invites params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserInvitesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get current user invites params
func (o *GetCurrentUserInvitesParams) WithTimeout(timeout time.Duration) *GetCurrentUserInvitesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current user invites params
func (o *GetCurrentUserInvitesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current user invites params
func (o *GetCurrentUserInvitesParams) WithContext(ctx context.Context) *GetCurrentUserInvitesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current user invites params
func (o *GetCurrentUserInvitesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current user invites params
func (o *GetCurrentUserInvitesParams) WithHTTPClient(client *http.Client) *GetCurrentUserInvitesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current user invites params
func (o *GetCurrentUserInvitesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserInvitesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
