// Code generated by go-swagger; DO NOT EDIT.

package current_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCurrentUserGroupsParams creates a new GetCurrentUserGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCurrentUserGroupsParams() *GetCurrentUserGroupsParams {
	return &GetCurrentUserGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserGroupsParamsWithTimeout creates a new GetCurrentUserGroupsParams object
// with the ability to set a timeout on a request.
func NewGetCurrentUserGroupsParamsWithTimeout(timeout time.Duration) *GetCurrentUserGroupsParams {
	return &GetCurrentUserGroupsParams{
		timeout: timeout,
	}
}

// NewGetCurrentUserGroupsParamsWithContext creates a new GetCurrentUserGroupsParams object
// with the ability to set a context for a request.
func NewGetCurrentUserGroupsParamsWithContext(ctx context.Context) *GetCurrentUserGroupsParams {
	return &GetCurrentUserGroupsParams{
		Context: ctx,
	}
}

// NewGetCurrentUserGroupsParamsWithHTTPClient creates a new GetCurrentUserGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCurrentUserGroupsParamsWithHTTPClient(client *http.Client) *GetCurrentUserGroupsParams {
	return &GetCurrentUserGroupsParams{
		HTTPClient: client,
	}
}

/* GetCurrentUserGroupsParams contains all the parameters to send to the API endpoint
   for the get current user groups operation.

   Typically these are written to a http.Request.
*/
type GetCurrentUserGroupsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get current user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserGroupsParams) WithDefaults() *GetCurrentUserGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get current user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get current user groups params
func (o *GetCurrentUserGroupsParams) WithTimeout(timeout time.Duration) *GetCurrentUserGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current user groups params
func (o *GetCurrentUserGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current user groups params
func (o *GetCurrentUserGroupsParams) WithContext(ctx context.Context) *GetCurrentUserGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current user groups params
func (o *GetCurrentUserGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current user groups params
func (o *GetCurrentUserGroupsParams) WithHTTPClient(client *http.Client) *GetCurrentUserGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current user groups params
func (o *GetCurrentUserGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
