// Code generated by go-swagger; DO NOT EDIT.

package current_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mnimidamonbackend/models"
)

// GetCurrentUserInvitesReader is a Reader for the GetCurrentUserInvites structure.
type GetCurrentUserInvitesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCurrentUserInvitesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCurrentUserInvitesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCurrentUserInvitesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetCurrentUserInvitesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCurrentUserInvitesOK creates a GetCurrentUserInvitesOK with default headers values
func NewGetCurrentUserInvitesOK() *GetCurrentUserInvitesOK {
	return &GetCurrentUserInvitesOK{}
}

/* GetCurrentUserInvitesOK describes a response with status code 200, with default header values.

Array of current user active group invites.
*/
type GetCurrentUserInvitesOK struct {
	Payload []*models.Invite
}

func (o *GetCurrentUserInvitesOK) Error() string {
	return fmt.Sprintf("[GET /users/current/invites][%d] getCurrentUserInvitesOK  %+v", 200, o.Payload)
}
func (o *GetCurrentUserInvitesOK) GetPayload() []*models.Invite {
	return o.Payload
}

func (o *GetCurrentUserInvitesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCurrentUserInvitesUnauthorized creates a GetCurrentUserInvitesUnauthorized with default headers values
func NewGetCurrentUserInvitesUnauthorized() *GetCurrentUserInvitesUnauthorized {
	return &GetCurrentUserInvitesUnauthorized{}
}

/* GetCurrentUserInvitesUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type GetCurrentUserInvitesUnauthorized struct {
	Payload *models.Error
}

func (o *GetCurrentUserInvitesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /users/current/invites][%d] getCurrentUserInvitesUnauthorized  %+v", 401, o.Payload)
}
func (o *GetCurrentUserInvitesUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCurrentUserInvitesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCurrentUserInvitesInternalServerError creates a GetCurrentUserInvitesInternalServerError with default headers values
func NewGetCurrentUserInvitesInternalServerError() *GetCurrentUserInvitesInternalServerError {
	return &GetCurrentUserInvitesInternalServerError{}
}

/* GetCurrentUserInvitesInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetCurrentUserInvitesInternalServerError struct {
	Payload *models.Error
}

func (o *GetCurrentUserInvitesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/current/invites][%d] getCurrentUserInvitesInternalServerError  %+v", 500, o.Payload)
}
func (o *GetCurrentUserInvitesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCurrentUserInvitesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
