// Code generated by go-swagger; DO NOT EDIT.

package invite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAcceptCurrentUserInviteParams creates a new AcceptCurrentUserInviteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAcceptCurrentUserInviteParams() *AcceptCurrentUserInviteParams {
	return &AcceptCurrentUserInviteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAcceptCurrentUserInviteParamsWithTimeout creates a new AcceptCurrentUserInviteParams object
// with the ability to set a timeout on a request.
func NewAcceptCurrentUserInviteParamsWithTimeout(timeout time.Duration) *AcceptCurrentUserInviteParams {
	return &AcceptCurrentUserInviteParams{
		timeout: timeout,
	}
}

// NewAcceptCurrentUserInviteParamsWithContext creates a new AcceptCurrentUserInviteParams object
// with the ability to set a context for a request.
func NewAcceptCurrentUserInviteParamsWithContext(ctx context.Context) *AcceptCurrentUserInviteParams {
	return &AcceptCurrentUserInviteParams{
		Context: ctx,
	}
}

// NewAcceptCurrentUserInviteParamsWithHTTPClient creates a new AcceptCurrentUserInviteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAcceptCurrentUserInviteParamsWithHTTPClient(client *http.Client) *AcceptCurrentUserInviteParams {
	return &AcceptCurrentUserInviteParams{
		HTTPClient: client,
	}
}

/* AcceptCurrentUserInviteParams contains all the parameters to send to the API endpoint
   for the accept current user invite operation.

   Typically these are written to a http.Request.
*/
type AcceptCurrentUserInviteParams struct {

	/* GroupID.

	   Numeric ID of the Invite.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the accept current user invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AcceptCurrentUserInviteParams) WithDefaults() *AcceptCurrentUserInviteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the accept current user invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AcceptCurrentUserInviteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the accept current user invite params
func (o *AcceptCurrentUserInviteParams) WithTimeout(timeout time.Duration) *AcceptCurrentUserInviteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the accept current user invite params
func (o *AcceptCurrentUserInviteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the accept current user invite params
func (o *AcceptCurrentUserInviteParams) WithContext(ctx context.Context) *AcceptCurrentUserInviteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the accept current user invite params
func (o *AcceptCurrentUserInviteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the accept current user invite params
func (o *AcceptCurrentUserInviteParams) WithHTTPClient(client *http.Client) *AcceptCurrentUserInviteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the accept current user invite params
func (o *AcceptCurrentUserInviteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the accept current user invite params
func (o *AcceptCurrentUserInviteParams) WithGroupID(groupID int64) *AcceptCurrentUserInviteParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the accept current user invite params
func (o *AcceptCurrentUserInviteParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *AcceptCurrentUserInviteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
