// Code generated by go-swagger; DO NOT EDIT.

package invite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeclineCurrentUserInviteParams creates a new DeclineCurrentUserInviteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeclineCurrentUserInviteParams() *DeclineCurrentUserInviteParams {
	return &DeclineCurrentUserInviteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeclineCurrentUserInviteParamsWithTimeout creates a new DeclineCurrentUserInviteParams object
// with the ability to set a timeout on a request.
func NewDeclineCurrentUserInviteParamsWithTimeout(timeout time.Duration) *DeclineCurrentUserInviteParams {
	return &DeclineCurrentUserInviteParams{
		timeout: timeout,
	}
}

// NewDeclineCurrentUserInviteParamsWithContext creates a new DeclineCurrentUserInviteParams object
// with the ability to set a context for a request.
func NewDeclineCurrentUserInviteParamsWithContext(ctx context.Context) *DeclineCurrentUserInviteParams {
	return &DeclineCurrentUserInviteParams{
		Context: ctx,
	}
}

// NewDeclineCurrentUserInviteParamsWithHTTPClient creates a new DeclineCurrentUserInviteParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeclineCurrentUserInviteParamsWithHTTPClient(client *http.Client) *DeclineCurrentUserInviteParams {
	return &DeclineCurrentUserInviteParams{
		HTTPClient: client,
	}
}

/* DeclineCurrentUserInviteParams contains all the parameters to send to the API endpoint
   for the decline current user invite operation.

   Typically these are written to a http.Request.
*/
type DeclineCurrentUserInviteParams struct {

	/* GroupID.

	   Numeric ID of the Invite.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the decline current user invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeclineCurrentUserInviteParams) WithDefaults() *DeclineCurrentUserInviteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the decline current user invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeclineCurrentUserInviteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the decline current user invite params
func (o *DeclineCurrentUserInviteParams) WithTimeout(timeout time.Duration) *DeclineCurrentUserInviteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the decline current user invite params
func (o *DeclineCurrentUserInviteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the decline current user invite params
func (o *DeclineCurrentUserInviteParams) WithContext(ctx context.Context) *DeclineCurrentUserInviteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the decline current user invite params
func (o *DeclineCurrentUserInviteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the decline current user invite params
func (o *DeclineCurrentUserInviteParams) WithHTTPClient(client *http.Client) *DeclineCurrentUserInviteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the decline current user invite params
func (o *DeclineCurrentUserInviteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the decline current user invite params
func (o *DeclineCurrentUserInviteParams) WithGroupID(groupID int64) *DeclineCurrentUserInviteParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the decline current user invite params
func (o *DeclineCurrentUserInviteParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *DeclineCurrentUserInviteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
