// Code generated by go-swagger; DO NOT EDIT.

package invite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCurrentUserInviteParams creates a new GetCurrentUserInviteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCurrentUserInviteParams() *GetCurrentUserInviteParams {
	return &GetCurrentUserInviteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserInviteParamsWithTimeout creates a new GetCurrentUserInviteParams object
// with the ability to set a timeout on a request.
func NewGetCurrentUserInviteParamsWithTimeout(timeout time.Duration) *GetCurrentUserInviteParams {
	return &GetCurrentUserInviteParams{
		timeout: timeout,
	}
}

// NewGetCurrentUserInviteParamsWithContext creates a new GetCurrentUserInviteParams object
// with the ability to set a context for a request.
func NewGetCurrentUserInviteParamsWithContext(ctx context.Context) *GetCurrentUserInviteParams {
	return &GetCurrentUserInviteParams{
		Context: ctx,
	}
}

// NewGetCurrentUserInviteParamsWithHTTPClient creates a new GetCurrentUserInviteParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCurrentUserInviteParamsWithHTTPClient(client *http.Client) *GetCurrentUserInviteParams {
	return &GetCurrentUserInviteParams{
		HTTPClient: client,
	}
}

/* GetCurrentUserInviteParams contains all the parameters to send to the API endpoint
   for the get current user invite operation.

   Typically these are written to a http.Request.
*/
type GetCurrentUserInviteParams struct {

	/* GroupID.

	   Numeric ID of the Invite.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get current user invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserInviteParams) WithDefaults() *GetCurrentUserInviteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get current user invite params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserInviteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get current user invite params
func (o *GetCurrentUserInviteParams) WithTimeout(timeout time.Duration) *GetCurrentUserInviteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current user invite params
func (o *GetCurrentUserInviteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current user invite params
func (o *GetCurrentUserInviteParams) WithContext(ctx context.Context) *GetCurrentUserInviteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current user invite params
func (o *GetCurrentUserInviteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current user invite params
func (o *GetCurrentUserInviteParams) WithHTTPClient(client *http.Client) *GetCurrentUserInviteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current user invite params
func (o *GetCurrentUserInviteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the get current user invite params
func (o *GetCurrentUserInviteParams) WithGroupID(groupID int64) *GetCurrentUserInviteParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the get current user invite params
func (o *GetCurrentUserInviteParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserInviteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
