// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetGroupBackupsParams creates a new GetGroupBackupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupBackupsParams() *GetGroupBackupsParams {
	return &GetGroupBackupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupBackupsParamsWithTimeout creates a new GetGroupBackupsParams object
// with the ability to set a timeout on a request.
func NewGetGroupBackupsParamsWithTimeout(timeout time.Duration) *GetGroupBackupsParams {
	return &GetGroupBackupsParams{
		timeout: timeout,
	}
}

// NewGetGroupBackupsParamsWithContext creates a new GetGroupBackupsParams object
// with the ability to set a context for a request.
func NewGetGroupBackupsParamsWithContext(ctx context.Context) *GetGroupBackupsParams {
	return &GetGroupBackupsParams{
		Context: ctx,
	}
}

// NewGetGroupBackupsParamsWithHTTPClient creates a new GetGroupBackupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupBackupsParamsWithHTTPClient(client *http.Client) *GetGroupBackupsParams {
	return &GetGroupBackupsParams{
		HTTPClient: client,
	}
}

/* GetGroupBackupsParams contains all the parameters to send to the API endpoint
   for the get group backups operation.

   Typically these are written to a http.Request.
*/
type GetGroupBackupsParams struct {

	/* GroupID.

	   Numeric ID of the Group.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get group backups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupBackupsParams) WithDefaults() *GetGroupBackupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get group backups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupBackupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get group backups params
func (o *GetGroupBackupsParams) WithTimeout(timeout time.Duration) *GetGroupBackupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group backups params
func (o *GetGroupBackupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group backups params
func (o *GetGroupBackupsParams) WithContext(ctx context.Context) *GetGroupBackupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group backups params
func (o *GetGroupBackupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group backups params
func (o *GetGroupBackupsParams) WithHTTPClient(client *http.Client) *GetGroupBackupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group backups params
func (o *GetGroupBackupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the get group backups params
func (o *GetGroupBackupsParams) WithGroupID(groupID int64) *GetGroupBackupsParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the get group backups params
func (o *GetGroupBackupsParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupBackupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
