// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetGroupBackupParams creates a new GetGroupBackupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetGroupBackupParams() *GetGroupBackupParams {
	return &GetGroupBackupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetGroupBackupParamsWithTimeout creates a new GetGroupBackupParams object
// with the ability to set a timeout on a request.
func NewGetGroupBackupParamsWithTimeout(timeout time.Duration) *GetGroupBackupParams {
	return &GetGroupBackupParams{
		timeout: timeout,
	}
}

// NewGetGroupBackupParamsWithContext creates a new GetGroupBackupParams object
// with the ability to set a context for a request.
func NewGetGroupBackupParamsWithContext(ctx context.Context) *GetGroupBackupParams {
	return &GetGroupBackupParams{
		Context: ctx,
	}
}

// NewGetGroupBackupParamsWithHTTPClient creates a new GetGroupBackupParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetGroupBackupParamsWithHTTPClient(client *http.Client) *GetGroupBackupParams {
	return &GetGroupBackupParams{
		HTTPClient: client,
	}
}

/* GetGroupBackupParams contains all the parameters to send to the API endpoint
   for the get group backup operation.

   Typically these are written to a http.Request.
*/
type GetGroupBackupParams struct {

	/* BackupID.

	   Numeric ID of the Backup.
	*/
	BackupID int64

	/* GroupID.

	   Numeric ID of the Model.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get group backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupBackupParams) WithDefaults() *GetGroupBackupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get group backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetGroupBackupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get group backup params
func (o *GetGroupBackupParams) WithTimeout(timeout time.Duration) *GetGroupBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get group backup params
func (o *GetGroupBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get group backup params
func (o *GetGroupBackupParams) WithContext(ctx context.Context) *GetGroupBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get group backup params
func (o *GetGroupBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get group backup params
func (o *GetGroupBackupParams) WithHTTPClient(client *http.Client) *GetGroupBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get group backup params
func (o *GetGroupBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackupID adds the backupID to the get group backup params
func (o *GetGroupBackupParams) WithBackupID(backupID int64) *GetGroupBackupParams {
	o.SetBackupID(backupID)
	return o
}

// SetBackupID adds the backupId to the get group backup params
func (o *GetGroupBackupParams) SetBackupID(backupID int64) {
	o.BackupID = backupID
}

// WithGroupID adds the groupID to the get group backup params
func (o *GetGroupBackupParams) WithGroupID(groupID int64) *GetGroupBackupParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the get group backup params
func (o *GetGroupBackupParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *GetGroupBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param backup_id
	if err := r.SetPathParam("backup_id", swag.FormatInt64(o.BackupID)); err != nil {
		return err
	}

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
