// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"mnimidamonbackend/models"
)

// NewInitializeGroupBackupParams creates a new InitializeGroupBackupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInitializeGroupBackupParams() *InitializeGroupBackupParams {
	return &InitializeGroupBackupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInitializeGroupBackupParamsWithTimeout creates a new InitializeGroupBackupParams object
// with the ability to set a timeout on a request.
func NewInitializeGroupBackupParamsWithTimeout(timeout time.Duration) *InitializeGroupBackupParams {
	return &InitializeGroupBackupParams{
		timeout: timeout,
	}
}

// NewInitializeGroupBackupParamsWithContext creates a new InitializeGroupBackupParams object
// with the ability to set a context for a request.
func NewInitializeGroupBackupParamsWithContext(ctx context.Context) *InitializeGroupBackupParams {
	return &InitializeGroupBackupParams{
		Context: ctx,
	}
}

// NewInitializeGroupBackupParamsWithHTTPClient creates a new InitializeGroupBackupParams object
// with the ability to set a custom HTTPClient for a request.
func NewInitializeGroupBackupParamsWithHTTPClient(client *http.Client) *InitializeGroupBackupParams {
	return &InitializeGroupBackupParams{
		HTTPClient: client,
	}
}

/* InitializeGroupBackupParams contains all the parameters to send to the API endpoint
   for the initialize group backup operation.

   Typically these are written to a http.Request.
*/
type InitializeGroupBackupParams struct {

	// Body.
	Body *models.InitializeGroupBackupPayload

	/* GroupID.

	   Numeric ID of the Model.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the initialize group backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InitializeGroupBackupParams) WithDefaults() *InitializeGroupBackupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the initialize group backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InitializeGroupBackupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the initialize group backup params
func (o *InitializeGroupBackupParams) WithTimeout(timeout time.Duration) *InitializeGroupBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the initialize group backup params
func (o *InitializeGroupBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the initialize group backup params
func (o *InitializeGroupBackupParams) WithContext(ctx context.Context) *InitializeGroupBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the initialize group backup params
func (o *InitializeGroupBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the initialize group backup params
func (o *InitializeGroupBackupParams) WithHTTPClient(client *http.Client) *InitializeGroupBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the initialize group backup params
func (o *InitializeGroupBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the initialize group backup params
func (o *InitializeGroupBackupParams) WithBody(body *models.InitializeGroupBackupPayload) *InitializeGroupBackupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the initialize group backup params
func (o *InitializeGroupBackupParams) SetBody(body *models.InitializeGroupBackupPayload) {
	o.Body = body
}

// WithGroupID adds the groupID to the initialize group backup params
func (o *InitializeGroupBackupParams) WithGroupID(groupID int64) *InitializeGroupBackupParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the initialize group backup params
func (o *InitializeGroupBackupParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *InitializeGroupBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
