// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mnimidamonbackend/models"
)

// LogComputerBackupReader is a Reader for the LogComputerBackup structure.
type LogComputerBackupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogComputerBackupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLogComputerBackupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLogComputerBackupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewLogComputerBackupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLogComputerBackupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLogComputerBackupOK creates a LogComputerBackupOK with default headers values
func NewLogComputerBackupOK() *LogComputerBackupOK {
	return &LogComputerBackupOK{}
}

/* LogComputerBackupOK describes a response with status code 200, with default header values.

The logged computer backup object
*/
type LogComputerBackupOK struct {
	Payload *models.GroupComputerBackup
}

func (o *LogComputerBackupOK) Error() string {
	return fmt.Sprintf("[POST /users/current/computers/current/groups/{group_id}/backups/{backup_id}/log][%d] logComputerBackupOK  %+v", 200, o.Payload)
}
func (o *LogComputerBackupOK) GetPayload() *models.GroupComputerBackup {
	return o.Payload
}

func (o *LogComputerBackupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupComputerBackup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogComputerBackupBadRequest creates a LogComputerBackupBadRequest with default headers values
func NewLogComputerBackupBadRequest() *LogComputerBackupBadRequest {
	return &LogComputerBackupBadRequest{}
}

/* LogComputerBackupBadRequest describes a response with status code 400, with default header values.

Supplied parameters were not okay.
*/
type LogComputerBackupBadRequest struct {
	Payload *models.Error
}

func (o *LogComputerBackupBadRequest) Error() string {
	return fmt.Sprintf("[POST /users/current/computers/current/groups/{group_id}/backups/{backup_id}/log][%d] logComputerBackupBadRequest  %+v", 400, o.Payload)
}
func (o *LogComputerBackupBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *LogComputerBackupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogComputerBackupUnauthorized creates a LogComputerBackupUnauthorized with default headers values
func NewLogComputerBackupUnauthorized() *LogComputerBackupUnauthorized {
	return &LogComputerBackupUnauthorized{}
}

/* LogComputerBackupUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type LogComputerBackupUnauthorized struct {
	Payload *models.Error
}

func (o *LogComputerBackupUnauthorized) Error() string {
	return fmt.Sprintf("[POST /users/current/computers/current/groups/{group_id}/backups/{backup_id}/log][%d] logComputerBackupUnauthorized  %+v", 401, o.Payload)
}
func (o *LogComputerBackupUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *LogComputerBackupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLogComputerBackupInternalServerError creates a LogComputerBackupInternalServerError with default headers values
func NewLogComputerBackupInternalServerError() *LogComputerBackupInternalServerError {
	return &LogComputerBackupInternalServerError{}
}

/* LogComputerBackupInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type LogComputerBackupInternalServerError struct {
	Payload *models.Error
}

func (o *LogComputerBackupInternalServerError) Error() string {
	return fmt.Sprintf("[POST /users/current/computers/current/groups/{group_id}/backups/{backup_id}/log][%d] logComputerBackupInternalServerError  %+v", 500, o.Payload)
}
func (o *LogComputerBackupInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *LogComputerBackupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
