// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"mnimidamonbackend/models"
)

// NewLogComputerBackupParams creates a new LogComputerBackupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLogComputerBackupParams() *LogComputerBackupParams {
	return &LogComputerBackupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLogComputerBackupParamsWithTimeout creates a new LogComputerBackupParams object
// with the ability to set a timeout on a request.
func NewLogComputerBackupParamsWithTimeout(timeout time.Duration) *LogComputerBackupParams {
	return &LogComputerBackupParams{
		timeout: timeout,
	}
}

// NewLogComputerBackupParamsWithContext creates a new LogComputerBackupParams object
// with the ability to set a context for a request.
func NewLogComputerBackupParamsWithContext(ctx context.Context) *LogComputerBackupParams {
	return &LogComputerBackupParams{
		Context: ctx,
	}
}

// NewLogComputerBackupParamsWithHTTPClient creates a new LogComputerBackupParams object
// with the ability to set a custom HTTPClient for a request.
func NewLogComputerBackupParamsWithHTTPClient(client *http.Client) *LogComputerBackupParams {
	return &LogComputerBackupParams{
		HTTPClient: client,
	}
}

/* LogComputerBackupParams contains all the parameters to send to the API endpoint
   for the log computer backup operation.

   Typically these are written to a http.Request.
*/
type LogComputerBackupParams struct {

	/* BackupID.

	   Numeric ID of the Backup.
	*/
	BackupID int64

	// Body.
	Body *models.ConfirmDownloadPayload

	/* GroupID.

	   Numeric ID of the Group.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the log computer backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LogComputerBackupParams) WithDefaults() *LogComputerBackupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the log computer backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LogComputerBackupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the log computer backup params
func (o *LogComputerBackupParams) WithTimeout(timeout time.Duration) *LogComputerBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the log computer backup params
func (o *LogComputerBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the log computer backup params
func (o *LogComputerBackupParams) WithContext(ctx context.Context) *LogComputerBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the log computer backup params
func (o *LogComputerBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the log computer backup params
func (o *LogComputerBackupParams) WithHTTPClient(client *http.Client) *LogComputerBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the log computer backup params
func (o *LogComputerBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackupID adds the backupID to the log computer backup params
func (o *LogComputerBackupParams) WithBackupID(backupID int64) *LogComputerBackupParams {
	o.SetBackupID(backupID)
	return o
}

// SetBackupID adds the backupId to the log computer backup params
func (o *LogComputerBackupParams) SetBackupID(backupID int64) {
	o.BackupID = backupID
}

// WithBody adds the body to the log computer backup params
func (o *LogComputerBackupParams) WithBody(body *models.ConfirmDownloadPayload) *LogComputerBackupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the log computer backup params
func (o *LogComputerBackupParams) SetBody(body *models.ConfirmDownloadPayload) {
	o.Body = body
}

// WithGroupID adds the groupID to the log computer backup params
func (o *LogComputerBackupParams) WithGroupID(groupID int64) *LogComputerBackupParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the log computer backup params
func (o *LogComputerBackupParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *LogComputerBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param backup_id
	if err := r.SetPathParam("backup_id", swag.FormatInt64(o.BackupID)); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
