// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRequestBackupUploadParams creates a new RequestBackupUploadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRequestBackupUploadParams() *RequestBackupUploadParams {
	return &RequestBackupUploadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRequestBackupUploadParamsWithTimeout creates a new RequestBackupUploadParams object
// with the ability to set a timeout on a request.
func NewRequestBackupUploadParamsWithTimeout(timeout time.Duration) *RequestBackupUploadParams {
	return &RequestBackupUploadParams{
		timeout: timeout,
	}
}

// NewRequestBackupUploadParamsWithContext creates a new RequestBackupUploadParams object
// with the ability to set a context for a request.
func NewRequestBackupUploadParamsWithContext(ctx context.Context) *RequestBackupUploadParams {
	return &RequestBackupUploadParams{
		Context: ctx,
	}
}

// NewRequestBackupUploadParamsWithHTTPClient creates a new RequestBackupUploadParams object
// with the ability to set a custom HTTPClient for a request.
func NewRequestBackupUploadParamsWithHTTPClient(client *http.Client) *RequestBackupUploadParams {
	return &RequestBackupUploadParams{
		HTTPClient: client,
	}
}

/* RequestBackupUploadParams contains all the parameters to send to the API endpoint
   for the request backup upload operation.

   Typically these are written to a http.Request.
*/
type RequestBackupUploadParams struct {

	/* BackupID.

	   Numeric ID of the Backup.
	*/
	BackupID int64

	/* GroupID.

	   Numeric ID of the Group.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the request backup upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RequestBackupUploadParams) WithDefaults() *RequestBackupUploadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the request backup upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RequestBackupUploadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the request backup upload params
func (o *RequestBackupUploadParams) WithTimeout(timeout time.Duration) *RequestBackupUploadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request backup upload params
func (o *RequestBackupUploadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request backup upload params
func (o *RequestBackupUploadParams) WithContext(ctx context.Context) *RequestBackupUploadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request backup upload params
func (o *RequestBackupUploadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request backup upload params
func (o *RequestBackupUploadParams) WithHTTPClient(client *http.Client) *RequestBackupUploadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request backup upload params
func (o *RequestBackupUploadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackupID adds the backupID to the request backup upload params
func (o *RequestBackupUploadParams) WithBackupID(backupID int64) *RequestBackupUploadParams {
	o.SetBackupID(backupID)
	return o
}

// SetBackupID adds the backupId to the request backup upload params
func (o *RequestBackupUploadParams) SetBackupID(backupID int64) {
	o.BackupID = backupID
}

// WithGroupID adds the groupID to the request backup upload params
func (o *RequestBackupUploadParams) WithGroupID(groupID int64) *RequestBackupUploadParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the request backup upload params
func (o *RequestBackupUploadParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *RequestBackupUploadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param backup_id
	if err := r.SetPathParam("backup_id", swag.FormatInt64(o.BackupID)); err != nil {
		return err
	}

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
