// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUploadBackupParams creates a new UploadBackupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUploadBackupParams() *UploadBackupParams {
	return &UploadBackupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUploadBackupParamsWithTimeout creates a new UploadBackupParams object
// with the ability to set a timeout on a request.
func NewUploadBackupParamsWithTimeout(timeout time.Duration) *UploadBackupParams {
	return &UploadBackupParams{
		timeout: timeout,
	}
}

// NewUploadBackupParamsWithContext creates a new UploadBackupParams object
// with the ability to set a context for a request.
func NewUploadBackupParamsWithContext(ctx context.Context) *UploadBackupParams {
	return &UploadBackupParams{
		Context: ctx,
	}
}

// NewUploadBackupParamsWithHTTPClient creates a new UploadBackupParams object
// with the ability to set a custom HTTPClient for a request.
func NewUploadBackupParamsWithHTTPClient(client *http.Client) *UploadBackupParams {
	return &UploadBackupParams{
		HTTPClient: client,
	}
}

/* UploadBackupParams contains all the parameters to send to the API endpoint
   for the upload backup operation.

   Typically these are written to a http.Request.
*/
type UploadBackupParams struct {

	/* BackupData.

	   The encodec backup file.
	*/
	BackupData runtime.NamedReadCloser

	/* BackupID.

	   Numeric ID of the Backup.
	*/
	BackupID int64

	/* GroupID.

	   Numeric ID of the Group.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the upload backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadBackupParams) WithDefaults() *UploadBackupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upload backup params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UploadBackupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upload backup params
func (o *UploadBackupParams) WithTimeout(timeout time.Duration) *UploadBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload backup params
func (o *UploadBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload backup params
func (o *UploadBackupParams) WithContext(ctx context.Context) *UploadBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload backup params
func (o *UploadBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload backup params
func (o *UploadBackupParams) WithHTTPClient(client *http.Client) *UploadBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload backup params
func (o *UploadBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackupData adds the backupData to the upload backup params
func (o *UploadBackupParams) WithBackupData(backupData runtime.NamedReadCloser) *UploadBackupParams {
	o.SetBackupData(backupData)
	return o
}

// SetBackupData adds the backupData to the upload backup params
func (o *UploadBackupParams) SetBackupData(backupData runtime.NamedReadCloser) {
	o.BackupData = backupData
}

// WithBackupID adds the backupID to the upload backup params
func (o *UploadBackupParams) WithBackupID(backupID int64) *UploadBackupParams {
	o.SetBackupID(backupID)
	return o
}

// SetBackupID adds the backupId to the upload backup params
func (o *UploadBackupParams) SetBackupID(backupID int64) {
	o.BackupID = backupID
}

// WithGroupID adds the groupID to the upload backup params
func (o *UploadBackupParams) WithGroupID(groupID int64) *UploadBackupParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the upload backup params
func (o *UploadBackupParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *UploadBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.BackupData != nil {

		if o.BackupData != nil {
			// form file param backup_data
			if err := r.SetFileParam("backup_data", o.BackupData); err != nil {
				return err
			}
		}
	}

	// path param backup_id
	if err := r.SetPathParam("backup_id", swag.FormatInt64(o.BackupID)); err != nil {
		return err
	}

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
