// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mnimidamonbackend/models"
)

// LoginUserReader is a Reader for the LoginUser structure.
type LoginUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LoginUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLoginUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewLoginUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLoginUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLoginUserOK creates a LoginUserOK with default headers values
func NewLoginUserOK() *LoginUserOK {
	return &LoginUserOK{}
}

/* LoginUserOK describes a response with status code 200, with default header values.

Api key and profile response.
*/
type LoginUserOK struct {
	Payload *models.RegisterResponse
}

func (o *LoginUserOK) Error() string {
	return fmt.Sprintf("[POST /users/login][%d] loginUserOK  %+v", 200, o.Payload)
}
func (o *LoginUserOK) GetPayload() *models.RegisterResponse {
	return o.Payload
}

func (o *LoginUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RegisterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginUserUnauthorized creates a LoginUserUnauthorized with default headers values
func NewLoginUserUnauthorized() *LoginUserUnauthorized {
	return &LoginUserUnauthorized{}
}

/* LoginUserUnauthorized describes a response with status code 401, with default header values.

Bad credentials.
*/
type LoginUserUnauthorized struct {
	Payload *models.Error
}

func (o *LoginUserUnauthorized) Error() string {
	return fmt.Sprintf("[POST /users/login][%d] loginUserUnauthorized  %+v", 401, o.Payload)
}
func (o *LoginUserUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *LoginUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLoginUserInternalServerError creates a LoginUserInternalServerError with default headers values
func NewLoginUserInternalServerError() *LoginUserInternalServerError {
	return &LoginUserInternalServerError{}
}

/* LoginUserInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type LoginUserInternalServerError struct {
	Payload *models.Error
}

func (o *LoginUserInternalServerError) Error() string {
	return fmt.Sprintf("[POST /users/login][%d] loginUserInternalServerError  %+v", 500, o.Payload)
}
func (o *LoginUserInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *LoginUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
