// Code generated by go-swagger; DO NOT EDIT.

package authorization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"mnimidamonbackend/models"
)

// NewRegisterComputerParams creates a new RegisterComputerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegisterComputerParams() *RegisterComputerParams {
	return &RegisterComputerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterComputerParamsWithTimeout creates a new RegisterComputerParams object
// with the ability to set a timeout on a request.
func NewRegisterComputerParamsWithTimeout(timeout time.Duration) *RegisterComputerParams {
	return &RegisterComputerParams{
		timeout: timeout,
	}
}

// NewRegisterComputerParamsWithContext creates a new RegisterComputerParams object
// with the ability to set a context for a request.
func NewRegisterComputerParamsWithContext(ctx context.Context) *RegisterComputerParams {
	return &RegisterComputerParams{
		Context: ctx,
	}
}

// NewRegisterComputerParamsWithHTTPClient creates a new RegisterComputerParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegisterComputerParamsWithHTTPClient(client *http.Client) *RegisterComputerParams {
	return &RegisterComputerParams{
		HTTPClient: client,
	}
}

/* RegisterComputerParams contains all the parameters to send to the API endpoint
   for the register computer operation.

   Typically these are written to a http.Request.
*/
type RegisterComputerParams struct {

	/* Body.

	   Payload to register a new computer
	*/
	Body *models.CreateComputerPayload

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the register computer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterComputerParams) WithDefaults() *RegisterComputerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the register computer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegisterComputerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the register computer params
func (o *RegisterComputerParams) WithTimeout(timeout time.Duration) *RegisterComputerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register computer params
func (o *RegisterComputerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register computer params
func (o *RegisterComputerParams) WithContext(ctx context.Context) *RegisterComputerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register computer params
func (o *RegisterComputerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register computer params
func (o *RegisterComputerParams) WithHTTPClient(client *http.Client) *RegisterComputerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register computer params
func (o *RegisterComputerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the register computer params
func (o *RegisterComputerParams) WithBody(body *models.CreateComputerPayload) *RegisterComputerParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the register computer params
func (o *RegisterComputerParams) SetBody(body *models.CreateComputerPayload) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterComputerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
