// Code generated by go-swagger; DO NOT EDIT.

package group_computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new group computer API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for group computer API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetGroupComputersOfComputer(params *GetGroupComputersOfComputerParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGroupComputersOfComputerOK, error)

	JoinComputerToGroup(params *JoinComputerToGroupParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*JoinComputerToGroupOK, error)

	LeaveComputerFromGroup(params *LeaveComputerFromGroupParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*LeaveComputerFromGroupNoContent, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetGroupComputersOfComputer gets group computers of computer
*/
func (a *Client) GetGroupComputersOfComputer(params *GetGroupComputersOfComputerParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetGroupComputersOfComputerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGroupComputersOfComputerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getGroupComputersOfComputer",
		Method:             "GET",
		PathPattern:        "/users/current/computers/{computer_id}/groups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetGroupComputersOfComputerReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetGroupComputersOfComputerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getGroupComputersOfComputer: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  JoinComputerToGroup join computer to group API
*/
func (a *Client) JoinComputerToGroup(params *JoinComputerToGroupParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*JoinComputerToGroupOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewJoinComputerToGroupParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "joinComputerToGroup",
		Method:             "POST",
		PathPattern:        "/users/current/computers/current/groups/{group_id}/join",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &JoinComputerToGroupReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*JoinComputerToGroupOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for joinComputerToGroup: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  LeaveComputerFromGroup leave computer from group API
*/
func (a *Client) LeaveComputerFromGroup(params *LeaveComputerFromGroupParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*LeaveComputerFromGroupNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLeaveComputerFromGroupParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "leaveComputerFromGroup",
		Method:             "POST",
		PathPattern:        "/users/current/computers/current/groups/{group_id}/leave",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &LeaveComputerFromGroupReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*LeaveComputerFromGroupNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for leaveComputerFromGroup: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
