// Code generated by go-swagger; DO NOT EDIT.

package group_computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLeaveComputerFromGroupParams creates a new LeaveComputerFromGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLeaveComputerFromGroupParams() *LeaveComputerFromGroupParams {
	return &LeaveComputerFromGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLeaveComputerFromGroupParamsWithTimeout creates a new LeaveComputerFromGroupParams object
// with the ability to set a timeout on a request.
func NewLeaveComputerFromGroupParamsWithTimeout(timeout time.Duration) *LeaveComputerFromGroupParams {
	return &LeaveComputerFromGroupParams{
		timeout: timeout,
	}
}

// NewLeaveComputerFromGroupParamsWithContext creates a new LeaveComputerFromGroupParams object
// with the ability to set a context for a request.
func NewLeaveComputerFromGroupParamsWithContext(ctx context.Context) *LeaveComputerFromGroupParams {
	return &LeaveComputerFromGroupParams{
		Context: ctx,
	}
}

// NewLeaveComputerFromGroupParamsWithHTTPClient creates a new LeaveComputerFromGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewLeaveComputerFromGroupParamsWithHTTPClient(client *http.Client) *LeaveComputerFromGroupParams {
	return &LeaveComputerFromGroupParams{
		HTTPClient: client,
	}
}

/* LeaveComputerFromGroupParams contains all the parameters to send to the API endpoint
   for the leave computer from group operation.

   Typically these are written to a http.Request.
*/
type LeaveComputerFromGroupParams struct {

	/* GroupID.

	   Numeric ID of the Group.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the leave computer from group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LeaveComputerFromGroupParams) WithDefaults() *LeaveComputerFromGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the leave computer from group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LeaveComputerFromGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the leave computer from group params
func (o *LeaveComputerFromGroupParams) WithTimeout(timeout time.Duration) *LeaveComputerFromGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the leave computer from group params
func (o *LeaveComputerFromGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the leave computer from group params
func (o *LeaveComputerFromGroupParams) WithContext(ctx context.Context) *LeaveComputerFromGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the leave computer from group params
func (o *LeaveComputerFromGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the leave computer from group params
func (o *LeaveComputerFromGroupParams) WithHTTPClient(client *http.Client) *LeaveComputerFromGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the leave computer from group params
func (o *LeaveComputerFromGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the leave computer from group params
func (o *LeaveComputerFromGroupParams) WithGroupID(groupID int64) *LeaveComputerFromGroupParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the leave computer from group params
func (o *LeaveComputerFromGroupParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *LeaveComputerFromGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
