// Code generated by go-swagger; DO NOT EDIT.

package group_computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mnimidamonbackend/models"
)

// LeaveComputerFromGroupReader is a Reader for the LeaveComputerFromGroup structure.
type LeaveComputerFromGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LeaveComputerFromGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewLeaveComputerFromGroupNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewLeaveComputerFromGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewLeaveComputerFromGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLeaveComputerFromGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLeaveComputerFromGroupNoContent creates a LeaveComputerFromGroupNoContent with default headers values
func NewLeaveComputerFromGroupNoContent() *LeaveComputerFromGroupNoContent {
	return &LeaveComputerFromGroupNoContent{}
}

/* LeaveComputerFromGroupNoContent describes a response with status code 204, with default header values.

Successful deletion
*/
type LeaveComputerFromGroupNoContent struct {
}

func (o *LeaveComputerFromGroupNoContent) Error() string {
	return fmt.Sprintf("[POST /users/current/computers/current/groups/{group_id}/leave][%d] leaveComputerFromGroupNoContent ", 204)
}

func (o *LeaveComputerFromGroupNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLeaveComputerFromGroupBadRequest creates a LeaveComputerFromGroupBadRequest with default headers values
func NewLeaveComputerFromGroupBadRequest() *LeaveComputerFromGroupBadRequest {
	return &LeaveComputerFromGroupBadRequest{}
}

/* LeaveComputerFromGroupBadRequest describes a response with status code 400, with default header values.

Supplied parameters were not okay.
*/
type LeaveComputerFromGroupBadRequest struct {
	Payload *models.Error
}

func (o *LeaveComputerFromGroupBadRequest) Error() string {
	return fmt.Sprintf("[POST /users/current/computers/current/groups/{group_id}/leave][%d] leaveComputerFromGroupBadRequest  %+v", 400, o.Payload)
}
func (o *LeaveComputerFromGroupBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *LeaveComputerFromGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLeaveComputerFromGroupUnauthorized creates a LeaveComputerFromGroupUnauthorized with default headers values
func NewLeaveComputerFromGroupUnauthorized() *LeaveComputerFromGroupUnauthorized {
	return &LeaveComputerFromGroupUnauthorized{}
}

/* LeaveComputerFromGroupUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type LeaveComputerFromGroupUnauthorized struct {
	Payload *models.Error
}

func (o *LeaveComputerFromGroupUnauthorized) Error() string {
	return fmt.Sprintf("[POST /users/current/computers/current/groups/{group_id}/leave][%d] leaveComputerFromGroupUnauthorized  %+v", 401, o.Payload)
}
func (o *LeaveComputerFromGroupUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *LeaveComputerFromGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLeaveComputerFromGroupInternalServerError creates a LeaveComputerFromGroupInternalServerError with default headers values
func NewLeaveComputerFromGroupInternalServerError() *LeaveComputerFromGroupInternalServerError {
	return &LeaveComputerFromGroupInternalServerError{}
}

/* LeaveComputerFromGroupInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type LeaveComputerFromGroupInternalServerError struct {
	Payload *models.Error
}

func (o *LeaveComputerFromGroupInternalServerError) Error() string {
	return fmt.Sprintf("[POST /users/current/computers/current/groups/{group_id}/leave][%d] leaveComputerFromGroupInternalServerError  %+v", 500, o.Payload)
}
func (o *LeaveComputerFromGroupInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *LeaveComputerFromGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
