// Code generated by go-swagger; DO NOT EDIT.

package group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mnimidamonbackend/models"
)

// CreateGroupReader is a Reader for the CreateGroup structure.
type CreateGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateGroupBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateGroupUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateGroupInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateGroupOK creates a CreateGroupOK with default headers values
func NewCreateGroupOK() *CreateGroupOK {
	return &CreateGroupOK{}
}

/* CreateGroupOK describes a response with status code 200, with default header values.

The new gorup.
*/
type CreateGroupOK struct {
	Payload *models.Group
}

func (o *CreateGroupOK) Error() string {
	return fmt.Sprintf("[POST /users/current/groups][%d] createGroupOK  %+v", 200, o.Payload)
}
func (o *CreateGroupOK) GetPayload() *models.Group {
	return o.Payload
}

func (o *CreateGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Group)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGroupBadRequest creates a CreateGroupBadRequest with default headers values
func NewCreateGroupBadRequest() *CreateGroupBadRequest {
	return &CreateGroupBadRequest{}
}

/* CreateGroupBadRequest describes a response with status code 400, with default header values.

Supplied parameters were not okay.
*/
type CreateGroupBadRequest struct {
	Payload *models.Error
}

func (o *CreateGroupBadRequest) Error() string {
	return fmt.Sprintf("[POST /users/current/groups][%d] createGroupBadRequest  %+v", 400, o.Payload)
}
func (o *CreateGroupBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateGroupBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGroupUnauthorized creates a CreateGroupUnauthorized with default headers values
func NewCreateGroupUnauthorized() *CreateGroupUnauthorized {
	return &CreateGroupUnauthorized{}
}

/* CreateGroupUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type CreateGroupUnauthorized struct {
	Payload *models.Error
}

func (o *CreateGroupUnauthorized) Error() string {
	return fmt.Sprintf("[POST /users/current/groups][%d] createGroupUnauthorized  %+v", 401, o.Payload)
}
func (o *CreateGroupUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateGroupUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGroupInternalServerError creates a CreateGroupInternalServerError with default headers values
func NewCreateGroupInternalServerError() *CreateGroupInternalServerError {
	return &CreateGroupInternalServerError{}
}

/* CreateGroupInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type CreateGroupInternalServerError struct {
	Payload *models.Error
}

func (o *CreateGroupInternalServerError) Error() string {
	return fmt.Sprintf("[POST /users/current/groups][%d] createGroupInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateGroupInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateGroupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
