// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new computer API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for computer API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetBackupLocations(params *GetBackupLocationsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBackupLocationsOK, error)

	GetCurrentComputer(params *GetCurrentComputerParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentComputerOK, error)

	GetCurrentUserComputer(params *GetCurrentUserComputerParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserComputerOK, error)

	GetCurrentUserComputers(params *GetCurrentUserComputersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserComputersOK, error)

	GetCurrentUserGroupComputers(params *GetCurrentUserGroupComputersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserGroupComputersOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetBackupLocations gets a list on which computers the backup is stored
*/
func (a *Client) GetBackupLocations(params *GetBackupLocationsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetBackupLocationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetBackupLocationsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getBackupLocations",
		Method:             "GET",
		PathPattern:        "/users/current/computers/current/groups/{group_id}/backups/{backup_id}/computers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetBackupLocationsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetBackupLocationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getBackupLocations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCurrentComputer gets current computer
*/
func (a *Client) GetCurrentComputer(params *GetCurrentComputerParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentComputerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCurrentComputerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getCurrentComputer",
		Method:             "GET",
		PathPattern:        "/users/current/computers/current",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCurrentComputerReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCurrentComputerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getCurrentComputer: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCurrentUserComputer gets a computer
*/
func (a *Client) GetCurrentUserComputer(params *GetCurrentUserComputerParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserComputerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCurrentUserComputerParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getCurrentUserComputer",
		Method:             "GET",
		PathPattern:        "/users/current/computers/{computer_id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCurrentUserComputerReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCurrentUserComputerOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getCurrentUserComputer: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCurrentUserComputers gets all computer of the current user
*/
func (a *Client) GetCurrentUserComputers(params *GetCurrentUserComputersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserComputersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCurrentUserComputersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getCurrentUserComputers",
		Method:             "GET",
		PathPattern:        "/users/current/computers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCurrentUserComputersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCurrentUserComputersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getCurrentUserComputers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetCurrentUserGroupComputers gets computers of a group
*/
func (a *Client) GetCurrentUserGroupComputers(params *GetCurrentUserGroupComputersParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetCurrentUserGroupComputersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCurrentUserGroupComputersParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getCurrentUserGroupComputers",
		Method:             "GET",
		PathPattern:        "/users/current/groups/{group_id}/computers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetCurrentUserGroupComputersReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCurrentUserGroupComputersOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getCurrentUserGroupComputers: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
