// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mnimidamonbackend/models"
)

// DeleteComputerReader is a Reader for the DeleteComputer structure.
type DeleteComputerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteComputerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteComputerNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteComputerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteComputerUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteComputerInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteComputerNoContent creates a DeleteComputerNoContent with default headers values
func NewDeleteComputerNoContent() *DeleteComputerNoContent {
	return &DeleteComputerNoContent{}
}

/* DeleteComputerNoContent describes a response with status code 204, with default header values.

Computer succesfully deleted
*/
type DeleteComputerNoContent struct {
}

func (o *DeleteComputerNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/current/computers/{computer_id}][%d] deleteComputerNoContent ", 204)
}

func (o *DeleteComputerNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteComputerBadRequest creates a DeleteComputerBadRequest with default headers values
func NewDeleteComputerBadRequest() *DeleteComputerBadRequest {
	return &DeleteComputerBadRequest{}
}

/* DeleteComputerBadRequest describes a response with status code 400, with default header values.

Supplied parameters were not okay.
*/
type DeleteComputerBadRequest struct {
	Payload *models.Error
}

func (o *DeleteComputerBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /users/current/computers/{computer_id}][%d] deleteComputerBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteComputerBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteComputerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteComputerUnauthorized creates a DeleteComputerUnauthorized with default headers values
func NewDeleteComputerUnauthorized() *DeleteComputerUnauthorized {
	return &DeleteComputerUnauthorized{}
}

/* DeleteComputerUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type DeleteComputerUnauthorized struct {
	Payload *models.Error
}

func (o *DeleteComputerUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /users/current/computers/{computer_id}][%d] deleteComputerUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteComputerUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteComputerUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteComputerInternalServerError creates a DeleteComputerInternalServerError with default headers values
func NewDeleteComputerInternalServerError() *DeleteComputerInternalServerError {
	return &DeleteComputerInternalServerError{}
}

/* DeleteComputerInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type DeleteComputerInternalServerError struct {
	Payload *models.Error
}

func (o *DeleteComputerInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /users/current/computers/{computer_id}][%d] deleteComputerInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteComputerInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteComputerInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
