// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCurrentComputerParams creates a new GetCurrentComputerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCurrentComputerParams() *GetCurrentComputerParams {
	return &GetCurrentComputerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentComputerParamsWithTimeout creates a new GetCurrentComputerParams object
// with the ability to set a timeout on a request.
func NewGetCurrentComputerParamsWithTimeout(timeout time.Duration) *GetCurrentComputerParams {
	return &GetCurrentComputerParams{
		timeout: timeout,
	}
}

// NewGetCurrentComputerParamsWithContext creates a new GetCurrentComputerParams object
// with the ability to set a context for a request.
func NewGetCurrentComputerParamsWithContext(ctx context.Context) *GetCurrentComputerParams {
	return &GetCurrentComputerParams{
		Context: ctx,
	}
}

// NewGetCurrentComputerParamsWithHTTPClient creates a new GetCurrentComputerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCurrentComputerParamsWithHTTPClient(client *http.Client) *GetCurrentComputerParams {
	return &GetCurrentComputerParams{
		HTTPClient: client,
	}
}

/* GetCurrentComputerParams contains all the parameters to send to the API endpoint
   for the get current computer operation.

   Typically these are written to a http.Request.
*/
type GetCurrentComputerParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get current computer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentComputerParams) WithDefaults() *GetCurrentComputerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get current computer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentComputerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get current computer params
func (o *GetCurrentComputerParams) WithTimeout(timeout time.Duration) *GetCurrentComputerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current computer params
func (o *GetCurrentComputerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current computer params
func (o *GetCurrentComputerParams) WithContext(ctx context.Context) *GetCurrentComputerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current computer params
func (o *GetCurrentComputerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current computer params
func (o *GetCurrentComputerParams) WithHTTPClient(client *http.Client) *GetCurrentComputerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current computer params
func (o *GetCurrentComputerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentComputerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
