// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCurrentUserComputerParams creates a new GetCurrentUserComputerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCurrentUserComputerParams() *GetCurrentUserComputerParams {
	return &GetCurrentUserComputerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserComputerParamsWithTimeout creates a new GetCurrentUserComputerParams object
// with the ability to set a timeout on a request.
func NewGetCurrentUserComputerParamsWithTimeout(timeout time.Duration) *GetCurrentUserComputerParams {
	return &GetCurrentUserComputerParams{
		timeout: timeout,
	}
}

// NewGetCurrentUserComputerParamsWithContext creates a new GetCurrentUserComputerParams object
// with the ability to set a context for a request.
func NewGetCurrentUserComputerParamsWithContext(ctx context.Context) *GetCurrentUserComputerParams {
	return &GetCurrentUserComputerParams{
		Context: ctx,
	}
}

// NewGetCurrentUserComputerParamsWithHTTPClient creates a new GetCurrentUserComputerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCurrentUserComputerParamsWithHTTPClient(client *http.Client) *GetCurrentUserComputerParams {
	return &GetCurrentUserComputerParams{
		HTTPClient: client,
	}
}

/* GetCurrentUserComputerParams contains all the parameters to send to the API endpoint
   for the get current user computer operation.

   Typically these are written to a http.Request.
*/
type GetCurrentUserComputerParams struct {

	/* ComputerID.

	   Numeric ID of the Computer.
	*/
	ComputerID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get current user computer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserComputerParams) WithDefaults() *GetCurrentUserComputerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get current user computer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserComputerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get current user computer params
func (o *GetCurrentUserComputerParams) WithTimeout(timeout time.Duration) *GetCurrentUserComputerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current user computer params
func (o *GetCurrentUserComputerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current user computer params
func (o *GetCurrentUserComputerParams) WithContext(ctx context.Context) *GetCurrentUserComputerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current user computer params
func (o *GetCurrentUserComputerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current user computer params
func (o *GetCurrentUserComputerParams) WithHTTPClient(client *http.Client) *GetCurrentUserComputerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current user computer params
func (o *GetCurrentUserComputerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComputerID adds the computerID to the get current user computer params
func (o *GetCurrentUserComputerParams) WithComputerID(computerID int64) *GetCurrentUserComputerParams {
	o.SetComputerID(computerID)
	return o
}

// SetComputerID adds the computerId to the get current user computer params
func (o *GetCurrentUserComputerParams) SetComputerID(computerID int64) {
	o.ComputerID = computerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserComputerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param computer_id
	if err := r.SetPathParam("computer_id", swag.FormatInt64(o.ComputerID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
