// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCurrentUserComputersParams creates a new GetCurrentUserComputersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCurrentUserComputersParams() *GetCurrentUserComputersParams {
	return &GetCurrentUserComputersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserComputersParamsWithTimeout creates a new GetCurrentUserComputersParams object
// with the ability to set a timeout on a request.
func NewGetCurrentUserComputersParamsWithTimeout(timeout time.Duration) *GetCurrentUserComputersParams {
	return &GetCurrentUserComputersParams{
		timeout: timeout,
	}
}

// NewGetCurrentUserComputersParamsWithContext creates a new GetCurrentUserComputersParams object
// with the ability to set a context for a request.
func NewGetCurrentUserComputersParamsWithContext(ctx context.Context) *GetCurrentUserComputersParams {
	return &GetCurrentUserComputersParams{
		Context: ctx,
	}
}

// NewGetCurrentUserComputersParamsWithHTTPClient creates a new GetCurrentUserComputersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCurrentUserComputersParamsWithHTTPClient(client *http.Client) *GetCurrentUserComputersParams {
	return &GetCurrentUserComputersParams{
		HTTPClient: client,
	}
}

/* GetCurrentUserComputersParams contains all the parameters to send to the API endpoint
   for the get current user computers operation.

   Typically these are written to a http.Request.
*/
type GetCurrentUserComputersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get current user computers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserComputersParams) WithDefaults() *GetCurrentUserComputersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get current user computers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserComputersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get current user computers params
func (o *GetCurrentUserComputersParams) WithTimeout(timeout time.Duration) *GetCurrentUserComputersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current user computers params
func (o *GetCurrentUserComputersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current user computers params
func (o *GetCurrentUserComputersParams) WithContext(ctx context.Context) *GetCurrentUserComputersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current user computers params
func (o *GetCurrentUserComputersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current user computers params
func (o *GetCurrentUserComputersParams) WithHTTPClient(client *http.Client) *GetCurrentUserComputersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current user computers params
func (o *GetCurrentUserComputersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserComputersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
