// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetBackupLocationsParams creates a new GetBackupLocationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBackupLocationsParams() *GetBackupLocationsParams {
	return &GetBackupLocationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBackupLocationsParamsWithTimeout creates a new GetBackupLocationsParams object
// with the ability to set a timeout on a request.
func NewGetBackupLocationsParamsWithTimeout(timeout time.Duration) *GetBackupLocationsParams {
	return &GetBackupLocationsParams{
		timeout: timeout,
	}
}

// NewGetBackupLocationsParamsWithContext creates a new GetBackupLocationsParams object
// with the ability to set a context for a request.
func NewGetBackupLocationsParamsWithContext(ctx context.Context) *GetBackupLocationsParams {
	return &GetBackupLocationsParams{
		Context: ctx,
	}
}

// NewGetBackupLocationsParamsWithHTTPClient creates a new GetBackupLocationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBackupLocationsParamsWithHTTPClient(client *http.Client) *GetBackupLocationsParams {
	return &GetBackupLocationsParams{
		HTTPClient: client,
	}
}

/* GetBackupLocationsParams contains all the parameters to send to the API endpoint
   for the get backup locations operation.

   Typically these are written to a http.Request.
*/
type GetBackupLocationsParams struct {

	/* BackupID.

	   Numeric ID of the Backup.
	*/
	BackupID int64

	/* GroupID.

	   Numeric ID of the Group.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get backup locations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBackupLocationsParams) WithDefaults() *GetBackupLocationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get backup locations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBackupLocationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get backup locations params
func (o *GetBackupLocationsParams) WithTimeout(timeout time.Duration) *GetBackupLocationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get backup locations params
func (o *GetBackupLocationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get backup locations params
func (o *GetBackupLocationsParams) WithContext(ctx context.Context) *GetBackupLocationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get backup locations params
func (o *GetBackupLocationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get backup locations params
func (o *GetBackupLocationsParams) WithHTTPClient(client *http.Client) *GetBackupLocationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get backup locations params
func (o *GetBackupLocationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBackupID adds the backupID to the get backup locations params
func (o *GetBackupLocationsParams) WithBackupID(backupID int64) *GetBackupLocationsParams {
	o.SetBackupID(backupID)
	return o
}

// SetBackupID adds the backupId to the get backup locations params
func (o *GetBackupLocationsParams) SetBackupID(backupID int64) {
	o.BackupID = backupID
}

// WithGroupID adds the groupID to the get backup locations params
func (o *GetBackupLocationsParams) WithGroupID(groupID int64) *GetBackupLocationsParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the get backup locations params
func (o *GetBackupLocationsParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *GetBackupLocationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param backup_id
	if err := r.SetPathParam("backup_id", swag.FormatInt64(o.BackupID)); err != nil {
		return err
	}

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
