// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCurrentUserGroupComputersParams creates a new GetCurrentUserGroupComputersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCurrentUserGroupComputersParams() *GetCurrentUserGroupComputersParams {
	return &GetCurrentUserGroupComputersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserGroupComputersParamsWithTimeout creates a new GetCurrentUserGroupComputersParams object
// with the ability to set a timeout on a request.
func NewGetCurrentUserGroupComputersParamsWithTimeout(timeout time.Duration) *GetCurrentUserGroupComputersParams {
	return &GetCurrentUserGroupComputersParams{
		timeout: timeout,
	}
}

// NewGetCurrentUserGroupComputersParamsWithContext creates a new GetCurrentUserGroupComputersParams object
// with the ability to set a context for a request.
func NewGetCurrentUserGroupComputersParamsWithContext(ctx context.Context) *GetCurrentUserGroupComputersParams {
	return &GetCurrentUserGroupComputersParams{
		Context: ctx,
	}
}

// NewGetCurrentUserGroupComputersParamsWithHTTPClient creates a new GetCurrentUserGroupComputersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCurrentUserGroupComputersParamsWithHTTPClient(client *http.Client) *GetCurrentUserGroupComputersParams {
	return &GetCurrentUserGroupComputersParams{
		HTTPClient: client,
	}
}

/* GetCurrentUserGroupComputersParams contains all the parameters to send to the API endpoint
   for the get current user group computers operation.

   Typically these are written to a http.Request.
*/
type GetCurrentUserGroupComputersParams struct {

	/* GroupID.

	   Numeric ID of the Group.
	*/
	GroupID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get current user group computers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserGroupComputersParams) WithDefaults() *GetCurrentUserGroupComputersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get current user group computers params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserGroupComputersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get current user group computers params
func (o *GetCurrentUserGroupComputersParams) WithTimeout(timeout time.Duration) *GetCurrentUserGroupComputersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current user group computers params
func (o *GetCurrentUserGroupComputersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current user group computers params
func (o *GetCurrentUserGroupComputersParams) WithContext(ctx context.Context) *GetCurrentUserGroupComputersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current user group computers params
func (o *GetCurrentUserGroupComputersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current user group computers params
func (o *GetCurrentUserGroupComputersParams) WithHTTPClient(client *http.Client) *GetCurrentUserGroupComputersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current user group computers params
func (o *GetCurrentUserGroupComputersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupID adds the groupID to the get current user group computers params
func (o *GetCurrentUserGroupComputersParams) WithGroupID(groupID int64) *GetCurrentUserGroupComputersParams {
	o.SetGroupID(groupID)
	return o
}

// SetGroupID adds the groupId to the get current user group computers params
func (o *GetCurrentUserGroupComputersParams) SetGroupID(groupID int64) {
	o.GroupID = groupID
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserGroupComputersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param group_id
	if err := r.SetPathParam("group_id", swag.FormatInt64(o.GroupID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
