// Code generated by go-swagger; DO NOT EDIT.

package computer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"mnimidamonbackend/models"
)

// GetBackupLocationsReader is a Reader for the GetBackupLocations structure.
type GetBackupLocationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBackupLocationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBackupLocationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBackupLocationsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBackupLocationsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBackupLocationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBackupLocationsOK creates a GetBackupLocationsOK with default headers values
func NewGetBackupLocationsOK() *GetBackupLocationsOK {
	return &GetBackupLocationsOK{}
}

/* GetBackupLocationsOK describes a response with status code 200, with default header values.

Users and their computers that have the backup
*/
type GetBackupLocationsOK struct {
	Payload models.StoredBackupsComputerResponse
}

func (o *GetBackupLocationsOK) Error() string {
	return fmt.Sprintf("[GET /users/current/computers/current/groups/{group_id}/backups/{backup_id}/computers][%d] getBackupLocationsOK  %+v", 200, o.Payload)
}
func (o *GetBackupLocationsOK) GetPayload() models.StoredBackupsComputerResponse {
	return o.Payload
}

func (o *GetBackupLocationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupLocationsUnauthorized creates a GetBackupLocationsUnauthorized with default headers values
func NewGetBackupLocationsUnauthorized() *GetBackupLocationsUnauthorized {
	return &GetBackupLocationsUnauthorized{}
}

/* GetBackupLocationsUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type GetBackupLocationsUnauthorized struct {
	Payload *models.Error
}

func (o *GetBackupLocationsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /users/current/computers/current/groups/{group_id}/backups/{backup_id}/computers][%d] getBackupLocationsUnauthorized  %+v", 401, o.Payload)
}
func (o *GetBackupLocationsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBackupLocationsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupLocationsNotFound creates a GetBackupLocationsNotFound with default headers values
func NewGetBackupLocationsNotFound() *GetBackupLocationsNotFound {
	return &GetBackupLocationsNotFound{}
}

/* GetBackupLocationsNotFound describes a response with status code 404, with default header values.

The specified resource was not found.
*/
type GetBackupLocationsNotFound struct {
	Payload *models.Error
}

func (o *GetBackupLocationsNotFound) Error() string {
	return fmt.Sprintf("[GET /users/current/computers/current/groups/{group_id}/backups/{backup_id}/computers][%d] getBackupLocationsNotFound  %+v", 404, o.Payload)
}
func (o *GetBackupLocationsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBackupLocationsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupLocationsInternalServerError creates a GetBackupLocationsInternalServerError with default headers values
func NewGetBackupLocationsInternalServerError() *GetBackupLocationsInternalServerError {
	return &GetBackupLocationsInternalServerError{}
}

/* GetBackupLocationsInternalServerError describes a response with status code 500, with default header values.

Internal server error.
*/
type GetBackupLocationsInternalServerError struct {
	Payload *models.Error
}

func (o *GetBackupLocationsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/current/computers/current/groups/{group_id}/backups/{backup_id}/computers][%d] getBackupLocationsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetBackupLocationsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBackupLocationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
