name: fyne cross

on:
  pull_request:
  push:

jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15.x
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Fyne Cross
        run: |
          go install github.com/fyne-io/fyne-cross
          go build github.com/fyne-io/fyne-cross
          PATH="$GOPATH/bin:$PATH"
      -
        name: Show files in bin
        run: |
          sudo apt-get install tree
          tree ..
      -
        name: Test Fyne Cross
        run: |
          ./fyne-cross windows -help
          ./fyne-cross darwin -help
          ./fyne-cross linux -help
      -
        name: Cross Compile Linux Binaries
        run: ./fyne-cross linux -arch=amd64,386,arm -app-id mnimidamon-client -dir . -icon ./public/mnimidamon-frontend-icon-png  -output . ./cmd/mnimidamon-client
      -
        name: Cross Compile Windows Binaries
        run:

          ./fyne-cross windows -arch=amd64,386 -app-id mnimidamon-client -dir . -icon ./public/mnimidamon-frontend-icon-png -output . ./cmd/mnimidamon-client
      -
        name: Cross Compile Darwin Binaries
        run: ./fyne-cross darwin -arch=amd64,386 -app-id mnimidamon-client -dir . -icon ./public/mnimidamon-frontend-icon-png  -output . ./cmd/mnimidamon-client
      -
        name: Show files in bin
        run: |
          tree .
      -
        name: Move artifacts
        run: |
          mv $GITHUB_WORKSPACE/dist/**/* $GITHUB_WORKSPACE/dist/
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xgo
          path: $GITHUB_WORKSPACE/dist/*
          if-no-files-found: error
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            $GITHUB_WORKSPACE/dist/*.tar.gz
            $GITHUB_WORKSPACE/dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}