name: build

on:
  pull_request:
  push:

jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15.x
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: dist
          prefix: mnimidamon-client
          targets: windows/386,windows/amd64,linux/386,linux/amd64,linux/arm,darwin/386,darwin/amd64
          v: true
          x: true
          race: false
          ldflags: -s -w
          pkg: cmd/mnimidamon-client/main.go
          buildmode: default
          working_dir: $GITHUB_WORKSPACE
      -
        name: Move artifacts
        run: |
          mv $GITHUB_WORKSPACE/dist/**/* $GITHUB_WORKSPACE/dist/
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xgo
          path: $GITHUB_WORKSPACE/dist/*
          if-no-files-found: error
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            $GITHUB_WORKSPACE/dist/*.tar.gz
            $GITHUB_WORKSPACE/dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}