// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateGroupComputerPayload Payload when you join a computer to a group
// Example: {"size":1024}
//
// swagger:model CreateGroupComputerPayload
type CreateGroupComputerPayload struct {

	// size
	// Minimum: 1
	Size int64 `json:"size,omitempty"`
}

// Validate validates this create group computer payload
func (m *CreateGroupComputerPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateGroupComputerPayload) validateSize(formats strfmt.Registry) error {
	if swag.IsZero(m.Size) { // not required
		return nil
	}

	if err := validate.MinimumInt("size", "body", m.Size, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create group computer payload based on context it is used
func (m *CreateGroupComputerPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateGroupComputerPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateGroupComputerPayload) UnmarshalBinary(b []byte) error {
	var res CreateGroupComputerPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
